### ISSUE TITLE
UI Switch GPU Mode does not change mode

### ISSUE THREAD

**Issue by alu18999959g** [enielrodriguez/optimus-gpu-switcher#16]
I currently have "nvidia" mode enabled with :

`sudo envycontrol -s nvidia --force-comp --coolbits 24`  from terminal.

...But i choose from the applet (Optimus GPU Switcher") "discret" or "hibrid" nothing happens...i try reboot but doesn't works, always is display nvidia on the applet.

Debian 13 Testing my system.

Thanks!

**Comment by enielrodriguez** [comment]
Hi, thanks for reporting the bug. As soon as I can, I'll build a test environment and try to fix the error.

**Comment by athulvis** [comment]
Having same issue with KDE Neon 5.27. Looks like admin access issue?

**Comment by enielrodriguez** [comment]
Sorry for the delay but I've been a bit busy. There was certainly a problem requesting root privileges.  
Please try updating the widget, and let me know if it works for you now.

**Comment by JakobEdvardsson** [comment]
I'm not sure if it is the same issue but i get the following error message. Fedora 38 with KDE Plasma. 

![Screenshot_20230724_223441](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/65956084/ebb1e967-78e1-46b6-a389-d49005e54ff7)

**Comment by alu18999959g** [comment]
> Sorry for the delay but I've been a bit busy. There was certainly a problem requesting root privileges. Please try updating the widget, and let me know if it works for you now.

Works for me! Thanks

**Comment by Labaman** [comment]
![image](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/30574992/f4ced904-afab-44d8-ac80-f22f74357004)
Same problem as @JakobEdvardsson.
Widget version 1.1.3
![image](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/30574992/75f6c7b3-451e-47e9-9e9b-f25df3010977)
kdesu is installed.

**Comment by JakobEdvardsson** [comment]
> ![image](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/30574992/f4ced904-afab-44d8-ac80-f22f74357004)
> Same problem as @JakobEdvardsson.
> Widget version: 1.1.3
> Distro: Arch
> KDE Plasma: 5.27.6
> ![image](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/30574992/75f6c7b3-451e-47e9-9e9b-f25df3010977)
> kdesu is installed.

Are you using Wayland or X11? I did a fresh install of my distro and tried with X11 and had no issue.
Unfortunately I was not able to use envycontrol with Wayland. Nvidia mode would apply according to envycontrol but my external monitors would not work. No issues on X11.

**Comment by Labaman** [comment]
@JakobEdvardsson X11
![image](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/30574992/6c9b5ce0-90ab-4091-b5cc-432851f26552)

**Comment by JakobEdvardsson** [comment]
> @JakobEdvardsson X11
> ![image](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/30574992/6c9b5ce0-90ab-4091-b5cc-432851f26552)
> 

My guess is that your not promoted to run as root user. So the application doesn't have permission. I'll have a look at it later today and see if I can figure something out. I believe that was the issue for me. I was only promoted once to run as root and accidentally pressed cancel and was not prompted again.

**Comment by Labaman** [comment]
> My guess is that your not prompted to run as root user. So the application doesn't have permission. I'll have a look at it later today and see if I can figure something out. I believe that was the issue for me. I was only promoted once to run as root and accidentally pressed cancel and was not prompted again.
That's right. Judging by the error, the widget script is trying to look for the kdesu executable file where it doesn't actually exist.

**Comment by enielrodriguez** [comment]
Yeah that's right. The funny thing is that I use Fedora 38 too. Previously I used pkexec instead of kdesu, but it didn't work for Nvidia mode due to an error accessing an environment variable.I'll check later to find a solution. Thanks for the feedback.

**Comment by enielrodriguez** [comment]
> ![image](https://user-images.githubusercontent.com/30574992/256128924-f4ced904-afab-44d8-ac80-f22f74357004.png) Same problem as @JakobEdvardsson. Widget version: 1.1.3 Distro: Arch KDE Plasma: 5.27.6 ![image](https://user-images.githubusercontent.com/30574992/256129240-75f6c7b3-451e-47e9-9e9b-f25df3010977.png) kdesu is installed.

The problem is that kdesu is not always in the environment variables, so I had to put the full path. Apparently the path is not the same in all distros.

**Comment by Labaman** [comment]
@enielrodriguez Maybe, but there's usually a symbolic link to that "scary full path" in some common /usr/bin (/bin)
![image](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/30574992/a15e9b76-d1cc-4781-8c80-5e208c73ce55)

**Comment by enielrodriguez** [comment]
> 

Apparently it is not in all distros:

> kdesu is installed (as part of kde-cli-tools) but is not in your $PATH by default. You can access the binary from /usr/lib/x86_64-linux-gnu/libexec/kf5/kdesu.

[Kdesu Not Working?](https://askubuntu.com/questions/1044354/kdesu-not-working)

In fact, that was what caused the error to @alu18999959g the author of this issue.

I almost forgot, I was wrong before, I use **Fedora**, but I tested the latest version in a **Debian** virtual machine. That's why it worked for me. It happens that in **Fedora**, as you say, the kdesu path is `/usr/libexec/kf5/kdesu`  not `/usr/lib/x86_64-linux-gnu/libexec/kf5/kdesu`.  

The solution goes more or less along that line that you say, check where kdesu is. I'll work on it, if you have any other ideas go ahead.

**Comment by enielrodriguez** [comment]
Version 1.1.4 tested on Debian and Fedora 38.  
Please update and tell me if it works for you too.

**Comment by alu18999959g** [comment]
Works!! on Debian 13 (Testing) version 1.1.4
