### ISSUE TITLE
Issue with root password

### ISSUE THREAD

**Issue by niveK77pur** [enielrodriguez/optimus-gpu-switcher#22]
Hello, first of all, thanks for this neat widget! I have tried and wasted A LOT of time on various hybrid GPU solutions, and envycontrol literally *just worked*:tm:. So I am doubly happy there is a companion widget to make things even nicer still!

---

I have a slight issue when changing modes, in that it seems to ask for the root user's password. My root user does not have a password, nor do I intend to set one. My current user is able to run `sudo`, so I was hoping to give permissions with my user and my password instead.

As stated in the screenshot/window, I understand it in a way that pressing the *Ignore* button allows me to do this; however the window simply closes and nothing happens.

This means I have no other choice than to set the mode from the terminal using envycontrol directly. It is a somewhat minor inconvenience, and I still find the widget very useful for seeing which mode is currently set.

![Screenshot_20230926_215351](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/10981161/64c9fd57-bd32-42e4-ab72-27d377d32167)

For example, if I run a `systemctl` command that requires sudo, but I have not provided sudo in the command line (i.e. `systemctl restart systemd-resolved`), then the following window pops up; so I know that it should in theory be possible to ask for the user password instead of the root password. Maybe this could be of help to address this issue.

![Screenshot_20230926_220206](https://github.com/enielrodriguez/optimus-gpu-switcher/assets/10981161/6fdf9565-7de9-414f-b8e1-bf8cb6f74493)

I hope I am not using an outdated version of the program, I directly downloaded it by right-clicking on the task bar and going *Add Widgets... > Get New Widgets... > Download New Plasma Widgets* and then searching and downloading this widget.

**Comment by enielrodriguez** [comment]
Hello! Sorry for the delay in answering you, I don't know why I'm not getting the notifications by email.
I'll take a look at the issue to see how to solve it. I will keep you up to date with any news.

**Comment by enielrodriguez** [comment]
I added an option to change the target user of the kdesu command. Maybe you can use it to solve this issue

**Comment by niveK77pur** [comment]
Thanks for getting back on this, and sorry for the delayed reply.

I have now updated this widget via the same menu from which I downloaded it via plasma. Now, I am also getting notifications on what is happening, which is a neat touch!

Regarding your command, this is the output I am getting (I ran this after updating the widget if that makes any difference).
```
$ kdesu -u myusername -t -c "envycontrol -s integrated"
ERROR: This operation requires root privileges
```

As a matter of fact, this is an error message from `envycontrol`, which is effectively asking me to use `sudo`. I have the exact same output if I run the command within double quotes directly as-is.

Running the following prompts me for my password in the terminal, but I don't know if this will also reflect via a pop up window similar to what I showed in my initial message. The following works as expected once I enter my password in the terminal.

```
$ kdesu -u myusername -t -c "sudo envycontrol -s integrated"
[sudo] password for myusername:
Switching to integrated mode
Successfully disabled nvidia-persistenced.service
Operation completed successfully
Please reboot your computer for changes to take effect!
```

**Comment by enielrodriguez** [comment]
Yes, you are right, it is a message from EnvyControl.  
Now it's not clear to me if you then need to specify your user or not. Try to see if it works for you only with `kdesu -t -c "sudo envycontrol -s integrated"`

**Comment by enielrodriguez** [comment]
I'm very sorry, but I had to revert the changes. They weren't working, I tried every combination I could think of and nothing. And they were also causing errors and adding more complexity to the code.  
In this case I recommend defining a password for the root user.

**Comment by niveK77pur** [comment]
Running `kdesu -t -c "sudo envycontrol -s integrated"` also pops up a window asking for my root password, when I click "ignore", I will be prompted for my password in the terminal however.

But thanks anyways for your attempts! I think I will just stick to plain `envycontrol` then if I need to change the mode!

**Comment by enielrodriguez** [comment]
Something similar happens if you run that command from the widget, somehow it is waiting for the password from a terminal (which does not exist), hence it does not work.  
I would love to do more but I ran out of ideas for a simple solution.
