### ISSUE TITLE
Root not work on Debian 12

### ISSUE THREAD

**Issue by ProgrammingHobby** [enielrodriguez/optimus-gpu-switcher#24]
Hello,
i installed Optimus GPU Switcher on Debian 12 64bit. By asking for root Password, the Password was never accepted. No GPU switch was performed.
Envycontrol an Console Mode as Root User works perfectly.
Can please you take a look an fix this issue?
Optimus GPU Switcher is a great tool and I would be happy if it also works under Debian 12.

**Comment by enielrodriguez** [comment]
Hi!, thanks for your feedback.  
As soon as I can I will take a look at it, perhaps it is related to some changes I made trying to solve issue #22.

**Comment by enielrodriguez** [comment]
I already released a new version (v1.4.0). Try that one and tell me if it works for you.

**Comment by ProgrammingHobby** [comment]
Unfortunately, this version does not work either.  KDESU lets me enter the password, but then discards it as not valid. It seems that with Debian 12 the whole thing has to be solved via pkexec. At least pkexec is shown as password dialog when I start the KDE Partition Manager under Debian 12, which also needs root rights.

**Comment by enielrodriguez** [comment]
Ok, I'm going to install a test environment to make sure it works.
Pkexec was my first option but when switching to Nvidia mode it gave an
error related to access to an environment variable, an issue that I was not
able to solve at the time.

**Comment by enielrodriguez** [comment]
Are you sure you have version 1.4.0 installed?  
I have already tested it and it works without problems on Debian 12 with KDE 5.27.

**Comment by ProgrammingHobby** [comment]
I apologize for my late reply. Yes, I have installed Debian 12 Stable 64bit. Cleanly separated with root account and user account, each with their own passwords. Maybe it is also because I have done everything so far in a Wayland session. I have to try it all again in an X11 session.

**Comment by enielrodriguez** [comment]
Well, I'm using X11, and apparently it's the only difference between my environment and yours.

**Comment by enielrodriguez** [comment]
I'm closing the issue due to lack of feedback.  
A couple of additional notes:  
- When trying to reproduce the error in a similar environment everything works fine.
- Maybe it's a user permissions issue.
